name: Build and Push python package

on:
  push:
    branches: [ devel ]

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Python 3.7
        uses: actions/setup-python@v1
        with:
            python-version: 3.7
      
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -U setuptools wheel build

      - name: Build
        run:  scripts/build.sh
          